# Generated by Django 4.2.30 on 2026-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(default=180, help_text='Package duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='time_period',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='flexible', max_length=20),
        ),
    ]
