# Generated by Django 4.2.30 on 2026-10-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_package_duration_package_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='guests_per_package',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
