# Generated by Django 4.2.30 on 2026-09-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('spa', 'Spa Access'), ('treatment', 'Treatment'), ('package', 'Package')], max_length=20),
        ),
    ]
